### ISSUE TITLE
Access to the path 'C:\Windows\TEMP\TransbankIntegrationPublic.pem' is denied

### ISSUE THREAD

**Issue by Corobori** [TransbankDevelopers/transbank-sdk-dotnet#115]
**Describe el bug**

¿ Es normal que el SDK requiere derecho de escritura en una carpeta sistema ? No me siento confortable cambiar estos derechos. 
 
**Para reproducir**

Tuve que otorgar los derechos en la carpeta para poder seguir .... 

**Comportamiento observado**

Arroja Access to the path 'C:\Windows\TEMP\TransbankIntegrationPublic.pem' is denied

**Comportamiento esperado**

Desplegar pantalla de pago

**Capturas de pantalla**

Si aplica, agrega aquí capturas de pantalla que ayuden a explicar tu problema.

**Versiones (por favor agrega aquí la siguiente información):**
- SDK: [e.g. 1.1.0]
- .NET Framework: 4.5

**Contexto adicional**

![2020-06-19_10-43-06](https://user-images.githubusercontent.com/9389257/85146523-a6c4d500-b21b-11ea-966d-ca49b257e560.jpg)

**Comment by afiebig** [comment]
Es una carpeta temporal donde se dejan los certificados para poder comunicarse con transbank. si no se pueden crear entonces no se puede realizar la configuración. No es al SDK a quien tienes que autorizar, sino a tu aplicación.

**Comment by Corobori** [comment]
Si lo entiendo que así es, y lo hice, pero no podría ser a través de una carpeta parte del sitio ? Yo tengo clientes que trabajan con hosting compartidos y no estoy seguro que me van a permitir hacer este cambio. ¿ Este cambio fue hecho desde cual versión del SDK ?
  

----------------------------------------

**Comment by sergiogonzalezc** [comment]
Hola,

He usado .Net hace varios años y me suena a un tema de permisos de tu
solución en el ambiente donde se está ejecutándo.. si estas usando el SDK
de Transbank para WebPayPlus pienso que estas usando Windows Server y
podria solucionarse con un permiso en el IIS:   Debes dar permiso de
lectura, escritura y ejecución a las cuentas IUSR y IIS_IUSRS. Y en el IIS
para tu sitio web debes habilitar la autentacion por formularios (Form
Autentication) y autenticación anónima. Mi humilde aporte.

Atte
SGC
