### ISSUE TITLE
No acepta decimales

### ISSUE THREAD

**Issue by scascalesageinfoes** [TransbankDevelopers/transbank-sdk-dotnet#116]
Hola

Al poner importe en decimales en el sample da error:
"Ocurrió un error en la transacción (Validar correcta configuración de parametros)."

`decimal amount = decimal.Parse("50.25", new System.Globalization.CultureInfo("en-GB", true));`

Por otro lado he leído acepta por defecto pesos, como lo hago para que el importe sea en dolares? Es decir, cambiar la moneda, con  configuration.PatPassCurrency  no es
Gracias

**Comment by afiebig** [comment]
Hola los decimales son para la moneda en UF, la configuración de Pesos / Dolares se aplica en el código de comercio por parte de transbank, sin embargo no se estan entregando nuevos códigos de comercios en dolares, salvo casos especiales que se deben tratar con el ejecutivo comercial.
