### ISSUE TITLE
Session nativa aspx rota

### ISSUE THREAD

**Issue by scascalesageinfoes** [TransbankDevelopers/transbank-sdk-dotnet#117]
Hola
En el ejemplo hace servir el localstorage porque al llamar a transbank y volver se pierde toda la sessión hastra el momento. Hay forma de solucionarlo?
VS2019 + FMk4.8 + WIn10
Thx

**Comment by gonzunigad** [comment]
Hola @scascalesageinfoes. Creo que se resuelve agregando <httpCookies httpOnlyCookies=“true” requireSSL=“true” /> dentro de <system.web> en Web.config ¿me confirmas?

**Comment by scascalesageinfoes** [comment]
Funcionó. DEscubrí q el problema sucede cuando tengo Session_Start implementado en global.asasx (aunque esté vacío)

**Comment by sergiogonzalezc** [comment]
Hola, esto se soluciona de una forma mas simple: debes guardar en una tabla los datos de la session, token, oc, id del pago, etc, pero ANTES de de enviar a Transbank, luego cuando vuelva el control a tu aplicacion, debes consultar en tu BD por ese SessionID o ese Id pago (mismo que habias enviado al WS de Transbank), Con eso recuperas la información. Al menos así lo solucioné yo.

**Comment by ffiebig** [comment]
Hay un tema con las cookies y nuevas versiones de los navegadores que están eliminando cookies que no estén configuradas con `SameSite=None` y `Secure`. 

Formas de solucionarlo es marcar las cookies con lo que menciono o la solución que da Sergio.

Voy a cerrar el tema, si necesitan otra alternativa lo pueden re abrir
