### ISSUE TITLE
Soporte para asp.net core

### ISSUE THREAD

**Issue by JJJGGGG** [TransbankDevelopers/transbank-sdk-dotnet#118]
Hola. No sé donde más preguntar esto.

Estoy desarrollando una página en Asp.Net Core y quería saber si tienen soporte. En la página de transbank sólo aparece para el framework .Net Y al instalar el paquete me aparece que está para .NetFramework, y no para .Net Core. Gracias.

**Comment by gearsolutionschile** [comment]
Cuando tendran soporte para Net Core ??

**Comment by gearsolutionschile** [comment]
y Net Standar?

**Comment by gearsolutionschile** [comment]
Alguna novedad con el soporte para .netstandar o .netcore?

**Comment by gonzunigad** [comment]
Hola! De momento no está en nuestro backlog agregar soporte para .NET Core.

**Comment by gearsolutionschile** [comment]
Ni hablar de NET 5 entonces? Como les ayudo?


[matias]



De: Gonzalo De Spirito ***@***.***>
Enviado el: lunes, 29 de marzo de 2021 12:21
Para: TransbankDevelopers/transbank-sdk-dotnet ***@***.***>
CC: Matias Espinoza ***@***.***>; Comment ***@***.***>
Asunto: Re: [TransbankDevelopers/transbank-sdk-dotnet] Soporte para asp.net core (#118)


Hola! De momento no está en nuestro backlog agregar soporte para .NET Core.

**Comment by gonzunigad** [comment]
Estamos analizandolo para el nuevo release, que viene pronto. 
Este nuevo release eliminará todo lo de SOAP y con eso podreiamos apuntar a .NET Standard 1.2

**Comment by gearsolutionschile** [comment]
Gonzalo, perfecto si necesitan ayuda y puedo aportar en algo me avisan.

Saludos,


[matias]



De: Gonzalo De Spirito ***@***.***>
Enviado el: martes, 30 de marzo de 2021 13:20
Para: TransbankDevelopers/transbank-sdk-dotnet ***@***.***>
CC: Matias Espinoza ***@***.***>; Comment ***@***.***>
Asunto: Re: [TransbankDevelopers/transbank-sdk-dotnet] Soporte para asp.net core (#118)


Estamos analizandolo para el nuevo release, que viene pronto.
Este nuevo release eliminará todo lo de SOAP y con eso podreiamos apuntar a .NET Standard 1.2

**Comment by ffiebig** [comment]
La versión 3.0 del SDK soporte .Net Standard 2.0

**Comment by naruxrawr** [comment]
Hola, estaba intentando desarrollar integración webpay plus con ASP.NET Core 3.1, pero por lo que leo no existe soporte para esto. mi consulta es si existe alguna alternativa de uso compatible con mi desarrollo.. 
Quedo atenta
