### ISSUE TITLE
Error 21

### ISSUE THREAD

**Issue by yanezricardo** [TransbankDevelopers/transbank-sdk-dotnet#150]
**Clientes reportan Error 21**

Tenemos más de un año usano la integración con el SDK de .Net, sin embargo desde hace un par de meses algunos clientes estan teniendo problemas para realizar los pagos. 

La Plataforma muestra el mensaje: Tu transacción no se pudo llevar a cabo. Ten en cuenta que ningún cargo fue realizado en tu tarjeta (Error 21).
 
**En nuestras pruebas no hemos logrado reproducir el error**

<img width="467" alt="image" src="https://user-images.githubusercontent.com/12382278/163205221-d8aec1f2-25d5-48e9-8319-10b61d066b76.png">

**Versiones:**
- SDK: 3.0.1
- .NET Framework: 4.7.2

**Comment by ffiebig** [comment]
Hola, el mejor canal para revisar estos problemas en producción es enviar un correo a soportweb@transbank.cl con los token de las transacciones para que te indiquen el problema. Saludos!
