### ISSUE TITLE
Integración Hash Angular

### ISSUE THREAD

**Issue by josepfs1995** [TransbankDevelopers/transbank-sdk-dotnet#152]
Hola estoy trabajando en la integración de Transbank en una Web Angular, al crear la transacción estoy mandando la url del redireccionamiento 
`http://dominio/#/booking/ending-booking/payment/kJbSUK?token_ws=token`

El problema raro es que no esta soportando los hash de angular y en esta tecnología es común ver este formato

Saludos

**Comment by mvarlic** [comment]
La característica que mencionas esta relacionada con el api, mas no con el sdk (que usa el api).
