### ISSUE TITLE
[Suggestion] Apply to Resharper licences

### ISSUE THREAD

**Issue by r0lan2** [TransbankDevelopers/transbank-sdk-dotnet#21]
Hi, 
I think you are not using Resharper in your code. As everyone know this product is not free BUT maybe you can apply to some free licences since this git project is open source?
Read: https://www.jetbrains.com/buy/opensource/

**Comment by afiebig** [comment]
I'm closing this issue, because we do not meet at least one of the criteria to apply for an open source licence.

Thanks for the advice.
