### ISSUE TITLE
[Suggestion] code smells found using Resharper

### ISSUE THREAD

**Issue by r0lan2** [TransbankDevelopers/transbank-sdk-dotnet#5]
Hi,
In order to have a code more robust and remove any code smell a good idea could be install Resharper(trial) in your local machine.. after that you can inspect your solution. Doing that you will find some code smells that you could remove easy.

see my screenshot:
![image](https://user-images.githubusercontent.com/777801/43543826-2e3c6822-959f-11e8-83e7-954ea12fec41.png)

**Comment by leosoto** [comment]
Thanks @r0lan2! Sounds much better than reporting 134 issues 😆.

We'll look into them!
