### ISSUE TITLE
This should say CLP or USD

### ISSUE THREAD

**Issue by afiebig** [TransbankDevelopers/transbank-sdk-dotnet#62]
I don't understand this comment. `DEFAULT'  means CLP or UF?. 

IIRC, it's CLP or USD depending on the "commerce code".

https://github.com/TransbankDevelopers/transbank-sdk-dotnet/blob/e0ba5c78f05fb6abcafc63d0c82676ba6fd21f83/Transbank/Patpass/PatPassByWebpayNormal.cs#L41

_Originally posted by @leosoto in https://github.com/TransbankDevelopers/transbank-sdk-dotnet/pull/55_

**Comment by leosoto** [comment]
Yes, so "Pesos o UF" as a comment next to `DEFAULT` is misleading or at least confusing.

**Comment by goncafa** [comment]
@afiebig this issue was solved on release 2.1.0?

**Comment by afiebig** [comment]
Yeah, but the pr did not close the issue.
