### ISSUE TITLE
Create unit test using Mock4Net of similar framework

### ISSUE THREAD

**Issue by r0lan2** [TransbankDevelopers/transbank-sdk-dotnet#8]
Hi,
I can see that you have missing tests related with the integration with TransbankApi. A good (I think) alternative is use Mock4Net in order to mock the calls to transbank Api. 
In order to use this framework (or other) you guys should upload valid examples related with valid inputs and expected outputs from this API. 
As I said I could help them with that if you upload  this examples :)

**Comment by afiebig** [comment]
Thanks @r0lan2. We are currently working in the API documentation so we will have tos examples in a few days.
